version: '3'

# Basically do the below (tested on Mac only)
# task start-all
# task stop-all
# task restart-all

tasks:
  info:
    desc: How to start
    cmds:
      - echo ". ./api/venv/bin/activate"
    silent: false
  show-links:
    desc: Links to the services
    cmds:
      - echo "FastAPI - http://localhost:8001"
      - echo "Next.js - http://localhost:3000"

  start-api:
    desc: Start the FastAPI service
    cmds:
      - ./task-start-fastapi.sh
      - echo "FastAPI - http://localhost:8001"
    silent: false
  stop-api:
    desc: Stop the FastAPI service
    cmds:
      - pkill -f 'uvicorn main:app'
      - sleep 1

  install-nextjs-deps:
    desc: Install Next.js Dependencies
    cmds:
      - cd web-nextjs && npm install
    silent: false
  start-nextjs:
    desc: Start the Next.js service
    cmds:
      - ./task-start-nextjs.sh
    silent: false
  stop-nextjs:
    desc: Start the Next.js service
    cmds:
      - pkill -f 'npm run dev'
      - sleep 1
    silent: false

  clean-all:
    desc: Clean Logs
    cmds:
      - sleep 1
      - rm api/_fastapi.log
      - rm api/_fastapi.pid
      - rm web-nextjs/_nextjs.log
      - rm web-nextjs/_nextjs.pid
      - rm -rf web-nextjs/.next
    silent: false
    ignore_error: true

  start:
    desc: Start both FastAPI and Next.js services
    deps:
      - start-api
      - start-nextjs
      - show-links

  stop-all:
    desc: Stop both FastAPI and Next.js services
    deps:
      - stop-api
      - stop-nextjs
      - clean-all

  restart:
    desc: Restart both FastAPI and Next.js services
    deps:
      - stop-all
      - start-all